<?php
return [
    'default' => 'central',
    'connections' => [
        'central' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', 'postgres-central'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'central_management'),
            'username' => env('DB_USERNAME', 'laravel_user'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
        'pgsql' => [
            'driver' => 'pgsql',
            'host' => env('DB_HOST', 'postgres-central'),
            'port' => env('DB_PORT', '5432'),
            'database' => env('DB_DATABASE', 'central_management'),
            'username' => env('DB_USERNAME', 'laravel_user'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
        'pgsql_tenant' => [
            'driver' => 'pgsql',
            'host' => env('TENANCY_DB_HOST', 'postgres-tenants'),
            'port' => env('TENANCY_DB_PORT', '5432'),
            'database' => env('TENANCY_DB_DATABASE', 'postgres'),
            'username' => env('TENANCY_DB_USERNAME', 'laravel_user'),
            'password' => env('TENANCY_DB_PASSWORD', ''),
            'charset' => 'utf8',
            'prefix' => '',
            'prefix_indexes' => true,
            'schema' => 'public',
            'sslmode' => 'prefer',
        ],
    ],
];
